// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: master_product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMasterProductBarcodeExists = `-- name: CheckMasterProductBarcodeExists :one
SELECT EXISTS(
  SELECT 1 FROM master_products WHERE barcode = $1
) AS exists
`

func (q *Queries) CheckMasterProductBarcodeExists(ctx context.Context, barcode string) (bool, error) {
	row := q.db.QueryRow(ctx, checkMasterProductBarcodeExists, barcode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countMasterProducts = `-- name: CountMasterProducts :one
SELECT COUNT(*) FROM master_products
`

func (q *Queries) CountMasterProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMasterProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMasterProduct = `-- name: CreateMasterProduct :one
INSERT INTO master_products (
  barcode, name, photo_url, photo_path, category_id, brand_id, unit, source, is_generated_barcode, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, barcode, name, photo_url, photo_path, category_id, brand_id, unit, source, is_generated_barcode, is_active, created_by, created_at, updated_at
`

type CreateMasterProductParams struct {
	Barcode            string      `json:"barcode"`
	Name               string      `json:"name"`
	PhotoUrl           pgtype.Text `json:"photo_url"`
	PhotoPath          pgtype.Text `json:"photo_path"`
	CategoryID         pgtype.UUID `json:"category_id"`
	BrandID            pgtype.UUID `json:"brand_id"`
	Unit               pgtype.Text `json:"unit"`
	Source             pgtype.Text `json:"source"`
	IsGeneratedBarcode pgtype.Bool `json:"is_generated_barcode"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateMasterProduct(ctx context.Context, arg CreateMasterProductParams) (MasterProduct, error) {
	row := q.db.QueryRow(ctx, createMasterProduct,
		arg.Barcode,
		arg.Name,
		arg.PhotoUrl,
		arg.PhotoPath,
		arg.CategoryID,
		arg.BrandID,
		arg.Unit,
		arg.Source,
		arg.IsGeneratedBarcode,
		arg.CreatedBy,
	)
	var i MasterProduct
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Name,
		&i.PhotoUrl,
		&i.PhotoPath,
		&i.CategoryID,
		&i.BrandID,
		&i.Unit,
		&i.Source,
		&i.IsGeneratedBarcode,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMasterProduct = `-- name: DeleteMasterProduct :exec
DELETE FROM master_products WHERE id = $1
`

func (q *Queries) DeleteMasterProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMasterProduct, id)
	return err
}

const deleteTransactionItemsByMasterProduct = `-- name: DeleteTransactionItemsByMasterProduct :exec
DELETE FROM transaction_items WHERE master_product_id = $1
`

func (q *Queries) DeleteTransactionItemsByMasterProduct(ctx context.Context, masterProductID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransactionItemsByMasterProduct, masterProductID)
	return err
}

const getMasterProduct = `-- name: GetMasterProduct :one
SELECT id, barcode, name, photo_url, photo_path, category_id, brand_id, unit, source, is_generated_barcode, is_active, created_by, created_at, updated_at FROM master_products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMasterProduct(ctx context.Context, id pgtype.UUID) (MasterProduct, error) {
	row := q.db.QueryRow(ctx, getMasterProduct, id)
	var i MasterProduct
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Name,
		&i.PhotoUrl,
		&i.PhotoPath,
		&i.CategoryID,
		&i.BrandID,
		&i.Unit,
		&i.Source,
		&i.IsGeneratedBarcode,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMasterProductByBarcode = `-- name: GetMasterProductByBarcode :one
SELECT id, barcode, name, photo_url, photo_path, category_id, brand_id, unit, source, is_generated_barcode, is_active, created_by, created_at, updated_at FROM master_products
WHERE barcode = $1 LIMIT 1
`

func (q *Queries) GetMasterProductByBarcode(ctx context.Context, barcode string) (MasterProduct, error) {
	row := q.db.QueryRow(ctx, getMasterProductByBarcode, barcode)
	var i MasterProduct
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Name,
		&i.PhotoUrl,
		&i.PhotoPath,
		&i.CategoryID,
		&i.BrandID,
		&i.Unit,
		&i.Source,
		&i.IsGeneratedBarcode,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMasterProducts = `-- name: ListMasterProducts :many
SELECT mp.id, mp.barcode, mp.name, mp.photo_url, mp.photo_path, mp.category_id, mp.brand_id, mp.unit, mp.source, mp.is_generated_barcode, mp.is_active, mp.created_by, mp.created_at, mp.updated_at, c.name as category_name
FROM master_products mp
LEFT JOIN categories c ON mp.category_id = c.id
ORDER BY mp.id
`

type ListMasterProductsRow struct {
	ID                 pgtype.UUID      `json:"id"`
	Barcode            string           `json:"barcode"`
	Name               string           `json:"name"`
	PhotoUrl           pgtype.Text      `json:"photo_url"`
	PhotoPath          pgtype.Text      `json:"photo_path"`
	CategoryID         pgtype.UUID      `json:"category_id"`
	BrandID            pgtype.UUID      `json:"brand_id"`
	Unit               pgtype.Text      `json:"unit"`
	Source             pgtype.Text      `json:"source"`
	IsGeneratedBarcode pgtype.Bool      `json:"is_generated_barcode"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedBy          pgtype.UUID      `json:"created_by"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	CategoryName       pgtype.Text      `json:"category_name"`
}

func (q *Queries) ListMasterProducts(ctx context.Context) ([]ListMasterProductsRow, error) {
	rows, err := q.db.Query(ctx, listMasterProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMasterProductsRow
	for rows.Next() {
		var i ListMasterProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Barcode,
			&i.Name,
			&i.PhotoUrl,
			&i.PhotoPath,
			&i.CategoryID,
			&i.BrandID,
			&i.Unit,
			&i.Source,
			&i.IsGeneratedBarcode,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
