// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: store_category.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreCategory = `-- name: CreateStoreCategory :one
INSERT INTO store_categories (store_id, name, slug) VALUES ($1, $2, $3) RETURNING id, store_id, name, slug, created_at, updated_at
`

type CreateStoreCategoryParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
}

func (q *Queries) CreateStoreCategory(ctx context.Context, arg CreateStoreCategoryParams) (StoreCategory, error) {
	row := q.db.QueryRow(ctx, createStoreCategory, arg.StoreID, arg.Name, arg.Slug)
	var i StoreCategory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllStoreCategories = `-- name: GetAllStoreCategories :many
SELECT id, store_id, name, slug, created_at, updated_at FROM store_categories WHERE store_id = $1 ORDER BY name ASC
`

func (q *Queries) GetAllStoreCategories(ctx context.Context, storeID pgtype.UUID) ([]StoreCategory, error) {
	rows, err := q.db.Query(ctx, getAllStoreCategories, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreCategory
	for rows.Next() {
		var i StoreCategory
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreCategoryByName = `-- name: GetStoreCategoryByName :one
SELECT id, store_id, name, slug, created_at, updated_at FROM store_categories WHERE store_id = $1 AND name = $2 LIMIT 1
`

type GetStoreCategoryByNameParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Name    string      `json:"name"`
}

func (q *Queries) GetStoreCategoryByName(ctx context.Context, arg GetStoreCategoryByNameParams) (StoreCategory, error) {
	row := q.db.QueryRow(ctx, getStoreCategoryByName, arg.StoreID, arg.Name)
	var i StoreCategory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
